* What is this
This is just my attempt to collect and document recipes of food that I have enjoyed over time. I dont expect this to be a super guide of great food. Just some tips and tricks and recipes I picked up along the way written down in a format that is easy for me to lookup and understand.

* Who am I
I am a south indian who grew up in Kerala with strong ties to Tamil Nadu, who spent significant part of my life living in both of these states. Growing up vegetarian with strong preference to it, most of the recipes here would be vegetarian with occassional egg added here and there. I have had the luck of growing up, and marrying into a family who produce just amazing food that I enjoy. So this is my attempt to document them so that as age catches up on me I dont end up forgetting these recipes when people who introduced these are no longer with me.

If anyone has recipes that you want to persist, please do raise an issue with your recipe and I ll take my time to cook it, try it and add it in a format that works well in this recipe and a thanks in advance to anyone who enriches this.

And a quick disclaimer - Lot of the recipes might be also from other sources like youtube(As I said earlier, this is just for me to easily keep up and not to forget). I ll try my best to provide references wherever I can
