* Milagu Kozhambu

** Source
This is a recipe I got from my father in law and I started making it because my wife really enjoys this. If you really like the taste of peppercorn and would like something spicy in your rice, this is an amazing choice.

** Skill levels
This is a relatively easy recipe to make and is really quick for anyone who wants to hash something out quickly in the middle of a work day or when you are really tired

** Recipe
For three peoplw
- Roast well in oil
  [ ] Pepper - 1 spoon
  [ ] Chillies - 2 nos
  [ ] Toor dal - 3/4 spoon
  [ ] Urad dal - 1/2 spoon
- Transfer to  mixie.
- Add 1 small nellikkai(leaving this as is not to change his original text. This is Indian gooseberry) size tamarind.
- Roast curry leaves in the left outOil , Hing to the mixture.
- Initially grind dry, then  add water & grind to liquid paste.
- In the pan, saute mustard in a spoon full of mustard & add one red chilly cut into small pieces.
- Pour the ground liquid from mixie to the above vessel, Add salt to taste & allow it to boil for few mins.


** How I eat this
As with most things my wife and I eat, I eat rice with some milagu kozhambu and curd. My wife really enjoys this with paruppu thogaiyal as well.
